# Nombre del microservicio
spring.application.name=ms-courses

# Puerto
server.port=8081

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:coursesdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2 (para ver la base de datos en el navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true